/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package de.gesellix.gradle.plugin.variants;

import org.gradle.api.Project;
import org.gradle.testfixtures.ProjectBuilder;
import org.junit.Test;

import static org.junit.Assert.assertNotNull;

/**
 * A simple unit test for the 'de.gesellix.gradle.plugin.variants.greeting' plugin.
 */
public class GradlePluginVariantsMcvePluginTest {

  @Test
  public void pluginRegistersATask() {
    // Create a test project and apply the plugin
    Project project = ProjectBuilder.builder().build();
    project.getPlugins().apply("de.gesellix.gradle.plugin.variants.greeting");

    // Verify the result
    assertNotNull(project.getTasks().findByName("greeting"));
  }
}
