/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package de.gesellix.gradle.plugin.variants;

import org.gradle.api.Plugin;
import org.gradle.api.Project;

/**
 * A simple 'hello world' plugin.
 */
public class GradlePluginVariantsMcvePlugin implements Plugin<Project> {

  public void apply(Project project) {
    // Register a task
    project.getTasks().register("greeting", task -> {
      task.doLast(s -> System.out.println("Hello from plugin 'de.gesellix.gradle.plugin.variants.greeting' (default variant)"));
    });
  }
}
